"""Drop image_file column – Supabase only

Revision ID: cfb7d7b24a3f
Revises: 5429c28f3a85
Create Date: 2026-04-19 16:03:26.753804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb7d7b24a3f'
down_revision = '5429c28f3a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.VARCHAR(length=20), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
